### ISSUE TITLE
Windows clusters should apply the kube-proxy image as well

### ISSUE THREAD

**Issue by jsturtevant** [Azure/azure-capi-cli-extension#109]
Currently we deploy calico but the kubeproxy image is missing https://github.com/Azure/azure-capi-cli-extension/blob/86d2687f081ca3bfcee7dbc21110daf31ef34c69/src/capi/azext_capi/custom.py#L438-L442

We can use clusterctl to grab https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/templates/addons/windows/calico/kube-proxy-windows.yaml and replace the kubernetes version with version configured to create the cluster

**Comment by mboersma** [comment]
Fixed by #116
