### ISSUE TITLE
`AZURE_LOCATION` should be used as the default for `--location`

### ISSUE THREAD

**Issue by mboersma** [Azure/azure-capi-cli-extension#120]
`az capi` tries to be parallel to or compatible with the Quick Start and CAPI/CAPZ docs, so we shouldn't require the `--location` argument if the user already has `AZURE_LOCATION` set in their environment.

**Comment by tal66** [comment]
Hi, I'd like to do this

**Comment by mboersma** [comment]
@tal66 please do! Let us know if you have any questions.
