### ISSUE TITLE
`--template` argument help could be improved

### ISSUE THREAD

**Issue by mboersma** [Azure/azure-capi-cli-extension#121]
It's not currently using the short-description field, and it should use the long-description field as a helpful pointer, like:
"You can use https://raw.githubusercontent.com/kubernetes-sigs/cluster-api-provider-azure/main/templates/cluster-template.yaml as a starting point for a custom template"

**Comment by ranakan19** [comment]
@mboersma I'm not able to add reviewers to the PR. Is that expected?

**Comment by mboersma** [comment]
> I'm not able to add reviewers to the PR

I think by default you can't do so unless you have a specific role assignment in this repo. I didn't do any extra work after setting this up, so it's probably at the default permissions.

I'll review this and I can assign others if you have someone in mind.

**Comment by ranakan19** [comment]
> I'll review this and I can assign others if you have someone in mind.

Thanks! I don't have anybody particular in mind to add atm.
