### ISSUE TITLE
Handle `-k` version with or without a "v" prefix

### ISSUE THREAD

**Issue by mboersma** [Azure/azure-capi-cli-extension#127]
This is such a common problem, I think it would be best if `az capi` could be agnostic and just add (or remove?) the prefix "v" from the argument as needed to normalize it, then use that consistently internally.

**Comment by DannyBrito** [comment]
We just update `az capi` to use "v" prefix for Kubernetes version on templates #116 : https://github.com/Azure/azure-capi-cli-extension/pull/116/commits/08345c81150bf4b73841713dee45f9f63c196877
 as it needs prefix for proper provisioning.
So, in that scenario `-k` could accept with prefix and without it and added it afterwards.
