### ISSUE TITLE
Create az-capi-cli roadmap for deprecation or GA

### ISSUE THREAD

**Issue by dtzar** [Azure/azure-capi-cli-extension#263]
Create a roadmap to either GA a subset of the existing functionality OR deprecate this extension all together providing a viable alternative.  

If you use this tool today, would appreciate comments in this issue on what aspects you use with this extension more specifically.

**Comment by bingbing8** [comment]
I use capz extention to run k8s e2e on a Microsoft internal pipeline. API server port 6443 is not considered known port and the access from internet to access to port 6443 are blocked by nsg for all Microsoft internal test subscription. With capz extension, peer the vnet in AKS infra rg and the vnet in k8s cluster rg and I was able to run tests on the nodes (target to api server port 6443 in k8s cluster) in management cluster and copy the log back to pipeline agent by kubelet command.

Do you have any recommendation what to use after this deprecation?

**Comment by mboersma** [comment]
The other use cases for `az capi` I'm aware of are these:
- CAPZ reference image pipelines: https://github.com/kubernetes-sigs/image-builder/blob/896c21a8414810aa53751c7cc7be42b719c666c6/images/capi/packer/azure/.pipelines/test-vhd.yaml#L102
- Windows testing: https://github.com/kubernetes-sigs/windows-testing/pull/430#event-12962762634

I think for CAPZ we plan to take an approach similar to Windows testing and replace `az capi` with a script.
