### ISSUE TITLE
Defaults in python code as well as templates

### ISSUE THREAD

**Issue by DannyBrito** [Azure/azure-capi-cli-extension#58]
For some important variables there are some defaults in python code and templates. There should only be one source of truth.

**Comment by mboersma** [comment]
One example is `KUBERNETES_VERSION`, which is currently [1.22.8 in custom.py](https://github.com/Azure/azure-capi-cli-extension/blob/main/src/capi/azext_capi/custom.py#L228) but [1.20.2 in some templates](https://github.com/Azure/azure-capi-cli-extension/blob/main/src/capi/azext_capi/templates/MachinePool.yaml#L12). The value in custom.py will win, but it's confusing for a developer or a reader of the code when they diverge. Even having a default in both places requires a developer to reason about which one wins, but ideally it would be obvious.

We didn't want to propose a fix in the issue description, but the obvious ones are:
- Remove overlapping defaults from custom.py, or
- Remove overlapping defaults from the jinja template files

**Comment by DannyBrito** [comment]
@devigned, I agree with @mboersma. Making sure that we only have a source of truth.
A slightly addition to removing the overlapping values will be to extract these defaults values into a standalone file that the python code and possible the jinja template could refer to.
