### ISSUE TITLE
Refactor/Restructure Custom File into smaller parts

### ISSUE THREAD

**Issue by DannyBrito** [Azure/azure-capi-cli-extension#88]
It will be beneficial to restructure `custom.py` into smaller part for better readability and maintenance
  
_Originally posted by @CecileRobertMichon in https://github.com/Azure/azure-capi-cli-extension/pull/86#discussion_r868645333_

- [ ] Restructure helper methods
- [ ]  Restructure command methods

**Comment by DannyBrito** [comment]
See #89 for restructure of part of helper methods

**Comment by mboersma** [comment]
I think @DannyBrito accomplished this through several followup PRs.
